// Generated by gencpp from file const_msg/pc_to_dsp.msg
// DO NOT EDIT!


#ifndef CONST_MSG_MESSAGE_PC_TO_DSP_H
#define CONST_MSG_MESSAGE_PC_TO_DSP_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace const_msg
{
template <class ContainerAllocator>
struct pc_to_dsp_
{
  typedef pc_to_dsp_<ContainerAllocator> Type;

  pc_to_dsp_()
    : Header()
    , flag_start_stop(0)
    , V1(0)
    , V2(0)
    , V3(0)
    , V4(0)
    , SendData_State(0)  {
    }
  pc_to_dsp_(const ContainerAllocator& _alloc)
    : Header(_alloc)
    , flag_start_stop(0)
    , V1(0)
    , V2(0)
    , V3(0)
    , V4(0)
    , SendData_State(0)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _Header_type;
  _Header_type Header;

   typedef uint8_t _flag_start_stop_type;
  _flag_start_stop_type flag_start_stop;

   typedef int16_t _V1_type;
  _V1_type V1;

   typedef int16_t _V2_type;
  _V2_type V2;

   typedef int16_t _V3_type;
  _V3_type V3;

   typedef int16_t _V4_type;
  _V4_type V4;

   typedef uint8_t _SendData_State_type;
  _SendData_State_type SendData_State;





  typedef boost::shared_ptr< ::const_msg::pc_to_dsp_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::const_msg::pc_to_dsp_<ContainerAllocator> const> ConstPtr;

}; // struct pc_to_dsp_

typedef ::const_msg::pc_to_dsp_<std::allocator<void> > pc_to_dsp;

typedef boost::shared_ptr< ::const_msg::pc_to_dsp > pc_to_dspPtr;
typedef boost::shared_ptr< ::const_msg::pc_to_dsp const> pc_to_dspConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::const_msg::pc_to_dsp_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::const_msg::pc_to_dsp_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace const_msg

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'sensor_msgs': ['/opt/ros/kinetic/share/sensor_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg'], 'const_msg': ['/home/bearli/competition_catkin_ws/src/const_msg/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::const_msg::pc_to_dsp_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::const_msg::pc_to_dsp_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::const_msg::pc_to_dsp_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::const_msg::pc_to_dsp_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::const_msg::pc_to_dsp_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::const_msg::pc_to_dsp_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::const_msg::pc_to_dsp_<ContainerAllocator> >
{
  static const char* value()
  {
    return "72744243899e1bab7337fbf15a335ac5";
  }

  static const char* value(const ::const_msg::pc_to_dsp_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x72744243899e1babULL;
  static const uint64_t static_value2 = 0x7337fbf15a335ac5ULL;
};

template<class ContainerAllocator>
struct DataType< ::const_msg::pc_to_dsp_<ContainerAllocator> >
{
  static const char* value()
  {
    return "const_msg/pc_to_dsp";
  }

  static const char* value(const ::const_msg::pc_to_dsp_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::const_msg::pc_to_dsp_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header Header\n\
uint8 flag_start_stop\n\
int16 V1\n\
int16 V2\n\
int16 V3\n\
int16 V4\n\
uint8 SendData_State\n\
\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n\
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
";
  }

  static const char* value(const ::const_msg::pc_to_dsp_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::const_msg::pc_to_dsp_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.Header);
      stream.next(m.flag_start_stop);
      stream.next(m.V1);
      stream.next(m.V2);
      stream.next(m.V3);
      stream.next(m.V4);
      stream.next(m.SendData_State);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct pc_to_dsp_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::const_msg::pc_to_dsp_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::const_msg::pc_to_dsp_<ContainerAllocator>& v)
  {
    s << indent << "Header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.Header);
    s << indent << "flag_start_stop: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.flag_start_stop);
    s << indent << "V1: ";
    Printer<int16_t>::stream(s, indent + "  ", v.V1);
    s << indent << "V2: ";
    Printer<int16_t>::stream(s, indent + "  ", v.V2);
    s << indent << "V3: ";
    Printer<int16_t>::stream(s, indent + "  ", v.V3);
    s << indent << "V4: ";
    Printer<int16_t>::stream(s, indent + "  ", v.V4);
    s << indent << "SendData_State: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.SendData_State);
  }
};

} // namespace message_operations
} // namespace ros

#endif // CONST_MSG_MESSAGE_PC_TO_DSP_H
